version: '3.8'

services:
  tooljet:
    image: tooljet/try:latest
    container_name: tooljet
    restart: unless-stopped
    ports:
      - "${HOST_PORT}:80"
    volumes:
      - tooljet_data:/var/lib/postgresql/13/main
    networks:
      - tooljet_network

volumes:
  tooljet_data:

networks:
  tooljet_network:
    driver: bridge
